name: Make Check

on:
  push:
    branches:
          - master
          - s390xci
  pull_request:
    branches:
          - master
          - xmlsec-1_2_x

jobs:
  check-ubuntu-openssl300:
    runs-on: [ self-hosted, linux, S390X ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - config_flags:
          - config_flags: --enable-static --enable-static-linking --without-nss --without-gcrypt --without-gnutls
          - config_flags: --enable-static --enable-static-linking --enable-ftp --enable-md5 --enable-gost --enable-gost2012 --without-openssl --without-nss --without-gcrypt
    steps:
    - name: install dependencies
      run: |
          sudo apt update
          sudo apt install -y automake autoconf libtool libtool-bin libltdl-dev libltdl7
          sudo apt install -y libxml2 libxml2-dev libxslt1.1 libxslt1-dev
          sudo apt install -y libssl1.1 libssl-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libnss3-tools libgcrypt20 libgcrypt20-dev libgnutls28-dev
    - uses: actions/checkout@v2
    - name: create-build-dirs
      run: |
          mkdir build.dir install.dir
    - name: configure
      working-directory: build.dir
      run: |
          ../autogen.sh --prefix=${GITHUB_WORKSPACE}/install.dir --enable-werror --enable-pedantic ${{ matrix.config_flags }}
    - name: make
      working-directory: build.dir
      run: |
          make
    - name: make check
      working-directory: build.dir
      run: |
          make check
    - name: make install
      working-directory: build.dir
      run: |
          make install

  check-ubuntu-openssl111:
    runs-on: [ self-hosted, linux, S390X ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - config_flags:
          - config_flags: --enable-static-linking=yes --without-nss --without-gcrypt --without-gnutls
    steps:
    - name: install dependencies
      run: |
          sudo apt update
          sudo apt install -y automake autoconf libtool libtool-bin libltdl-dev libltdl7
          sudo apt install -y libxml2 libxml2-dev libxslt1.1 libxslt1-dev
          sudo apt install -y wget
    - uses: actions/checkout@v2
    - name: create-build-dirs
      run: |
          mkdir build.dir install.dir
    - name: configure
      working-directory: build.dir
      run: |
          export LD_LIBRARY_PATH="/usr/local/openssl3/lib:/usr/local/openssl3/lib64:$LD_LIBRARY_PATH"
          ../autogen.sh --prefix=${GITHUB_WORKSPACE}/install.dir --enable-werror --enable-pedantic ${{ matrix.config_flags }}
    - name: make
      working-directory: build.dir
      run: |
          make
    - name: make check
      working-directory: build.dir
      run: |
          export LD_LIBRARY_PATH="/usr/local/openssl3/lib:/usr/local/openssl3/lib64:$LD_LIBRARY_PATH"
          make check
    - name: make install
      working-directory: build.dir
      run: |
          make install
